name: Check PR Label

on:
  pull_request_target:
    branches:
     - 'main'

jobs:
  Debug-Labels:
    runs-on: ubuntu-latest
    steps:
      - name: Print all PR labels
        run: |
          echo "Labels are: "
          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"

  Build-label-check:

    runs-on: ubuntu-latest

    if: ${{ !contains(github.event.pull_request_target.labels.*.name, 'Ready-to-Build') || join(github.event.pull_request_target.labels) == '' }}
    steps:
      - name: Fail if PR is not yet built
        run: |
          echo "This PR needs to be built before merging to the repository."
          exit 1
